apiVersion: v1
kind: Service
metadata:
  name: mozilla-contributions-service
spec:
  ports:
  - port: 3333
    targetPort: 3333
  selector:
    app: mozilla-contributions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozilla-contributions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mozilla-contributions
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: mozilla-contributions
    spec:
      hostname: mozilla-contributions
      containers:
        - name: mozilla-contributions
          image: michaelkohler/mozilla-contributions:<TAG>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: "300M"
            requests:
              cpu: "80m"
              memory: "80M"
          ports:
            - containerPort: 3333
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-github
                  key: github
            - name: CONNECT
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-connect
                  key: connect
