apiVersion: v1
kind: Service
metadata:
  name: mozilla-contributions-service
spec:
  ports:
  - port: 3333
    targetPort: 3333
  selector:
    app: mozilla-contributions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozilla-contributions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mozilla-contributions
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: mozilla-contributions
    spec:
      hostname: mozilla-contributions
      containers:
        - name: mozilla-contributions
          image: michaelkohler/mozilla-contributions:<TAG>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: "300M"
            requests:
              cpu: "80m"
              memory: "80M"
          ports:
            - containerPort: 3333
          env:
            - name: FETCH
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-fetch
                  key: fetch
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-github
                  key: token
            - name: GITHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-github
                  key: username
            - name: GITHUB_FILTER
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-github
                  key: filter
            - name: GITHUB_STOP_DATE
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-github
                  key: stopdate
            - name: COMMUNITY_PORTAL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-cp
                  key: username
            - name: DISCOURSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-discourse
                  key: username
            - name: WIKI_STOP_DATE
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-wiki
                  key: stopdate
            - name: WIKI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-wiki
                  key: username
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-db
                  key: hostname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-db
                  key: password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-db
                  key: database
            - name: DB_CONNECTIONS
              valueFrom:
                secretKeyRef:
                  name: mozilla-contributions-db
                  key: connections
